# Site settings
title: jdONeill
email: dev@jdoneill.com
description: geospatial wanderings
paginate: 5
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gh.jdoneill.com" # the base hostname & protocol for your site
twitter_username: jdoneill
github_username:  doneill
linkedin_username:  jdoneill

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
