# Site settings
title: jdONeill
email: dev@jdoneill.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdoneill.com" # the base hostname & protocol for your site
twitter_username: jdoneill
github_username:  doneill
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
